connections: # 要自动化部署的连接
  - ssh.web-02

remote_folder: "/home/ubuntu/go/web-go/"  # 远端的部署文件夹

frontend: # 前端部署配置
  pre_action: # 部署前置命令
    - "pwd"
  post_action: # 部署后置命令
    - "pwd"

backend: # 后端部署配置
  goos: linux # 部署目标操作系统
  goarch: amd64 # 部署目标cpu架构
  pre_action: # 部署前置命令
    - "rm -f /home/ubuntu/go/web-go/web-go"
  post_action: # 部署后置命令
    - "chmod 777 /home/ubuntu/go/web-go/web-go"
    - "/home/ubuntu/go/web-go/web-go app restart"